src/Entity/Restaurant.php
<?php

namespace App\Entity;

use App\Repository\RestaurantRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RestaurantRepository::class)
 */
class Restaurant
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\ManyToOne(targetEntity="City", inversedBy="restaurants")
     * @ORM\JoinColumn(name="city_id", referencedColumnName="id")
     */
    private $city;

    /**
     * @ORM\ManyToOne(targetEntity="User", inversedBy="restaurants")
     * @ORM\JoinColumn(name="owner_id", referencedColumnName="id")
     */
    private $owner;

    /**
     * @ORM\OneToMany(targetEntity=Media::class, mappedBy="restaurant", orphanRemoval=true)
     * @ORM\JoinColumn(nullable=false)
     */
    private $medias;

    /**
     * @ORM\OneToMany(targetEntity=Review::class, mappedBy="restaurant", orphanRemoval=true)
     * @ORM\JoinColumn(nullable=false)
     */
    private $reviews;

    /**
     * @ORM\Column(type="integer")
     */
    private $postalCode;

    public function __construct()
    {
        $this->reviews = new ArrayCollection();
        $this->medias = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection<int, Review>
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Review $review): self
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews[] = $review;
            $review->setRestaurant($this);
        }

        return $this;
    }

    public function removeReview(Review $review): self
    {
        if ($this->reviews->removeElement($review)) {
            // set the owning side to null (unless already changed)
            if ($review->getRestaurant() === $this) {
                $review->setRestaurant(null);
            }
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * @param mixed $city
     * @return Restaurant
     */
    public function setCity($city)
    {
        $this->city = $city;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getOwner()
    {
        return $this->owner;
    }

    /**
     * @param mixed $owner
     * @return Restaurant
     */
    public function setOwner($owner)
    {
        $this->owner = $owner;
        return $this;
    }

    /**
     * @return Collection<int, Review>
     */
    public function getMedias(): Collection
    {
        return $this->medias;
    }

    public function addMedia(Media $media): self
    {
        if (!$this->medias->contains($media)) {
            $this->medias[] = $media;
            $media->setRestaurant($this);
        }

        return $this;
    }

    public function removeMedia(Media $media): self
    {
        if ($this->medias->removeElement($media)) {
            // set the owning side to null (unless already changed)
            if ($media->getRestaurant() === $this) {
                $media->setRestaurant(null);
            }
        }

        return $this;
    }

    public function getAverageRating() {
        $sumRating = 0;
        foreach($this->reviews as $review){
            $sumRating += $review->getRating();
        }

        return $sumRating / count($this->reviews);
    }

    public function __toString()
    {
        return $this->name;
    }

    /**
     * @return mixed
     */
    public function getPostalCode()
    {
        return $this->postalCode;
    }

    /**
     * @param mixed $postalCode
     * @return Restaurant
     */
    public function setPostalCode($postalCode)
    {
        $this->postalCode = $postalCode;
        return $this;
    }
}

src/Form/RestaurantType.php
<?php

namespace App\Form;

use App\Entity\Restaurant;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RestaurantType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('city')
            ->add('postalCode')
            ->add('mediaFile', FileType::class, [
                'mapped' => false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Restaurant::class,
        ]);
    }
}

src/Controller/RestaurantController.php
<?php

namespace App\Controller;

use App\Entity\Media;
use App\Entity\Restaurant;
use App\Form\RestaurantType;
use App\Repository\RestaurantRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

/**
 * @Route("/restaurant")
 */
class RestaurantController extends AbstractController
{
    /**
     * @Route("/", name="app_restaurant_index", methods={"GET"})
     */
    public function index(RestaurantRepository $restaurantRepository): Response
    {
        return $this->render('restaurant/index.html.twig', [
            'restaurants' => $restaurantRepository->getNLastRestaurant(10),
        ]);


    }

    /**
     * @Route("/", name="app_restaurant_search", methods={"POST"})
     */
    public function searchByCodePostal(Request $request, RestaurantRepository $restaurantRepository): Response
    {
        $postalCode = $request->request->get('search');
        return $this->render('restaurant/index.html.twig', [
            'restaurants' => $restaurantRepository->getRestaurantsByPostalCode($postalCode),
        ]);
    }

    /**
     * @Route("/new", name="app_restaurant_new", methods={"GET", "POST"})
     */
    public function new(Request $request, RestaurantRepository $restaurantRepository, SluggerInterface $slugger): Response
    {
        $restaurant = new Restaurant();
        $form = $this->createForm(RestaurantType::class, $restaurant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $mediaFile = $form->get('mediaFile')->getData();
            $user = $this->get('security.token_storage')->getToken()->getUser();
            $restaurant->setOwner($user);
            if ($mediaFile) {
                $media = new Media();
                $media->setRestaurant($restaurant);
                $originalFilename = pathinfo($mediaFile->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$mediaFile->guessExtension();

                try {
                    $mediaFile->move(
                        'media/',
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }

                $media->setFile($newFilename);
            }

            $restaurantRepository->add($restaurant);
            return $this->redirectToRoute('app_restaurant_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('restaurant/new.html.twig', [
            'restaurant' => $restaurant,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_restaurant_show", methods={"GET"})
     */
    public function show(Restaurant $restaurant): Response
    {
        return $this->render('restaurant/show.html.twig', [
            'restaurant' => $restaurant,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_restaurant_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Restaurant $restaurant, RestaurantRepository $restaurantRepository): Response
    {
        $form = $this->createForm(RestaurantType::class, $restaurant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $restaurantRepository->add($restaurant);
            return $this->redirectToRoute('app_restaurant_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('restaurant/edit.html.twig', [
            'restaurant' => $restaurant,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_restaurant_delete", methods={"POST"})
     */
    public function delete(Request $request, Restaurant $restaurant, RestaurantRepository $restaurantRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$restaurant->getId(), $request->request->get('_token'))) {
            $restaurantRepository->remove($restaurant);
        }

        return $this->redirectToRoute('app_restaurant_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/restaurant/_delete_form.html.twig
<form method="post" action="{{ path('app_restaurant_delete', {'id': restaurant.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ restaurant.id) }}">
    <button class="btn">Delete</button>
</form>

templates/restaurant/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/restaurant/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Restaurant{% endblock %}

{% block body %}
    <h1>Edit Restaurant</h1>

    {{ include('restaurant/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_restaurant_index') }}">back to list</a>

    {{ include('restaurant/_delete_form.html.twig') }}
{% endblock %}

templates/restaurant/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}Restaurant index{% endblock %}

{% block body %}
    <h1>Restaurant index</h1>
    <form class="form-horizontal" target="{{ path('app_restaurant_search') }}" role="form" method="post">
        <label for="site-search">Restaurant par code postal:</label>
        <input type="search" id="site-search" name="search"
               aria-label="Search through site content">

        <button>Rechercher</button>
    </form>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Rating (Average)</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for restaurant in restaurants %}
            <tr>
                <td>{{ restaurant.id }}</td>
                <td>{{ restaurant.name }}</td>
                <td>{% if(restaurant.reviews|length > 0) %}{{  restaurant.averageRating  }}{% else %}N/A{% endif %}</td>
                <td>
                    <a href="{{ path('app_restaurant_show', {'id': restaurant.id}) }}">show</a>
                    <a href="{{ path('app_restaurant_edit', {'id': restaurant.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_restaurant_new') }}">Create new</a>
{% endblock %}

templates/restaurant/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Restaurant{% endblock %}

{% block body %}
    <h1>Create new Restaurant</h1>

    {{ include('restaurant/_form.html.twig') }}

    <a href="{{ path('app_restaurant_index') }}">back to list</a>
{% endblock %}

templates/restaurant/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Restaurant{% endblock %}

{% block body %}
    <h1>Restaurant</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ restaurant.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ restaurant.name }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_restaurant_index') }}">back to list</a>

    <a href="{{ path('app_restaurant_edit', {'id': restaurant.id}) }}">edit</a>

    {{ include('restaurant/_delete_form.html.twig') }}
{% endblock %}